# Generated by Django 4.1.2 on 2022-10-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_playedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedon',
            name='session_length',
            field=models.IntegerField(default=0),
        ),
    ]
